export const columns = [
  {
    key: 'fecha',
    title: 'Fecha',
    dataIndex: 'FechaParte',
    defaultSortOrder: 'ascend',
    sorter: (a, b) => a.FechaParte > b.FechaParte,
  },
  {
    key: 'Id',
    title: 'Caña Molida Bruta (C.M.B.)',
    dataIndex: 'MoliendaCanaBruta',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.MoliendaCanaBruta > b.MoliendaCanaBruta,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Rto % CMB Total',
    dataIndex: 'RendimientoCanaBruta',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.RendimientoCanaBruta > b.RendimientoCanaBruta,
    render: (value) => value?.toLocaleString('es-AR', { minimumFractionDigits: 3, maximumFractionDigits: 3 }),
  },
  {
    key: 'Id',
    title: 'Caña Molida Neta (C.M.N.) ',
    dataIndex: 'MoliendaCanaNeta',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.MoliendaCanaNeta > b.MoliendaCanaNeta,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Rto % CMN Total',
    dataIndex: 'RendimientoCanaNeta',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.RendimientoCanaNeta > b.RendimientoCanaNeta,
    render: (value) => value?.toLocaleString('es-AR', { minimumFractionDigits: 3, maximumFractionDigits: 3 }),
  },
  {
    key: 'Id',
    title: 'Azúcar Equivalente',
    dataIndex: 'AzucarEquivalente',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.AzucarEquivalente > b.AzucarEquivalente,
    render: (value) => value?.toLocaleString('es-AR', { minimumFractionDigits: 3, maximumFractionDigits: 3 }),
    
  },
  {
    key: 'Id',
    title: 'Total Azúcar Blanco',
    dataIndex: 'AzucarBlancoProducido',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.AzucarBlancoProducido > b.AzucarBlancoProducido,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Total Azúcar Crudo',
    dataIndex: 'AzucarCrudoProducido',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.AzucarCrudoProducido > b.AzucarCrudoProducido,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Azúcar Refinada',
    dataIndex: 'AzucarRefinado',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.AzucarRefinado > b.AzucarRefinado,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Azúcar orgnánica',
    dataIndex: 'AzucarOrganico',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.AzucarOrganico > b.AzucarOrganico,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Otros Azúcares',
    dataIndex: 'OtroAzucar',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.OtroAzucar > b.OtroAzucar,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Melaza',
    dataIndex: 'MelazaProducida',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.MelazaProducida > b.MelazaProducida,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  {
    key: 'Id',
    title: 'Alcohol Total Hidratado',
    dataIndex: 'AlcoholProducido',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.AlcoholProducido > b.AlcoholProducido,
    render: (text) => new Intl.NumberFormat('es-AR').format(text),
  },
  

]
